/**
 * ObsidianGitignore — creates and maintains a .gitignore for Obsidian vaults.
 *
 * Designed to be idempotent: calling ensureGitignore() on a vault that already
 * has all required rules is a no-op (no file write, no git commit needed).
 */

import fs from 'fs';
import path from 'path';
import { createLogger } from '../utils/logger.util';

const logger = createLogger('ObsidianGitignore');

// ── Content ────────────────────────────────────────────────────────────────

export const OBSIDIAN_GITIGNORE_CONTENT = `# Obsync — Auto-generated .gitignore
# Generated by Obsync on ${new Date().toISOString().split('T')[0]}
# Edit below this line to add your own rules

# ============================================================
# OBSIDIAN TRANSIENT FILES (never sync these)
# ============================================================

# Workspace state — different per device, causes constant conflicts
.obsidian/workspace.json
.obsidian/workspace-mobile.json
.obsidian/workspaces.json

# Cache — regenerated automatically, large, no value in syncing
.obsidian/cache
.obsidian/.cache

# Obsidian internal data that is device-specific
.obsidian/graph-cache.json

# ============================================================
# OBSIDIAN TRASH
# ============================================================
.trash/

# ============================================================
# OPERATING SYSTEM FILES
# ============================================================
.DS_Store
.DS_Store?
._*
.Spotlight-V100
.Trashes
ehthumbs.db
Thumbs.db
desktop.ini

# ============================================================
# SYNC TOOL FILES
# ============================================================
obsync-lock.json
.obsync-temp/

# ============================================================
# YOUR CUSTOM RULES BELOW
# ============================================================`.trim();

/** Minimum rules that must be present in any vault's .gitignore. */
const REQUIRED_RULES: readonly string[] = [
  '.obsidian/workspace.json',
  '.obsidian/workspace-mobile.json',
  '.obsidian/cache',
  '.trash/',
  '.DS_Store',
  'Thumbs.db',
  'obsync-lock.json',
];

// ── Result type ────────────────────────────────────────────────────────────

export interface GitignoreResult {
  created: boolean;
  updated: boolean;
  addedRules: string[];
}

// ── Manager ────────────────────────────────────────────────────────────────

export class GitignoreManager {
  /**
   * Ensure the vault has a .gitignore with all required Obsidian rules.
   *
   * - If no .gitignore exists → creates one from OBSIDIAN_GITIGNORE_CONTENT.
   * - If .gitignore exists but is missing rules → appends only the missing ones.
   * - If all rules are already present → no-op (returns { created:false, updated:false }).
   */
  async ensureGitignore(vaultPath: string): Promise<GitignoreResult> {
    const gitignorePath = path.join(vaultPath, '.gitignore');

    // Case 1: No .gitignore — create from scratch
    if (!fs.existsSync(gitignorePath)) {
      await fs.promises.writeFile(gitignorePath, OBSIDIAN_GITIGNORE_CONTENT, 'utf-8');
      logger.info(`Created .gitignore in ${vaultPath}`);
      return { created: true, updated: false, addedRules: [...REQUIRED_RULES] };
    }

    // Case 2: Exists — check for missing rules
    const existing = await fs.promises.readFile(gitignorePath, 'utf-8');
    const missingRules = REQUIRED_RULES.filter(rule => !existing.includes(rule));

    if (missingRules.length === 0) {
      return { created: false, updated: false, addedRules: [] };
    }

    // Append missing rules with a clear section header
    const addition = [
      '',
      '# Added by Obsync',
      ...missingRules,
    ].join('\n');

    await fs.promises.appendFile(gitignorePath, addition, 'utf-8');
    logger.info(`Updated .gitignore in ${vaultPath} (+${missingRules.length} rules)`);
    return { created: false, updated: true, addedRules: missingRules };
  }

  /**
   * Overwrite the .gitignore with the full Obsync default content.
   * Used by the "Reset to defaults" action in Settings.
   */
  async resetToDefaults(vaultPath: string): Promise<void> {
    const gitignorePath = path.join(vaultPath, '.gitignore');
    await fs.promises.writeFile(gitignorePath, OBSIDIAN_GITIGNORE_CONTENT, 'utf-8');
    logger.info(`Reset .gitignore to defaults in ${vaultPath}`);
  }

  /**
   * Read the current .gitignore content for display in the UI.
   * Returns null if the file doesn't exist.
   */
  async read(vaultPath: string): Promise<string | null> {
    const gitignorePath = path.join(vaultPath, '.gitignore');
    if (!fs.existsSync(gitignorePath)) return null;
    return fs.promises.readFile(gitignorePath, 'utf-8');
  }
}

/** Singleton instance — shared across the main process. */
export const gitignoreManager = new GitignoreManager();
